# Generated by Django 5.1.2 on 2024-10-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('avatar', models.ImageField(default='avatars/default-user-avatar.jpg', upload_to='avatars/')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
